### ISSUE TITLE
Game wont open (Making mod for Mari0)

### ISSUE THREAD

**Issue by VioletasTheThird** [hamsterready/love-console#23]
Hey, I am making a mod for mari0 and now the game wont open after i added the commands. Mari0 runs on love 0.8

**Comment by Positive07** [comment]
This console works with 0.9.2, and hasn't been updated for a long period of time

**Comment by shakesoda** [comment]
Try this version
https://github.com/excessive/ludum-dare-36/blob/master/libs/console.lua


- Colby

**Comment by JacobSinclair** [comment]
@Positive07 Aww ok. Due to the fact there is no error that displays I will try and edit it to work with 0.8 or I will use Mari0 SE which is made in 0.9.2

**Comment by Positive07** [comment]
I recommend you move to 0.9.2 if possible (or to 0.10.2) there have been several improvements in LÖVE, like scancodes, text input support and even the UTF-8 library
